---
- name: Reiniciar Serviço Windows 
  hosts: "{{ host_alvo }}"
  gather_facts: no

  tasks:
    - name: Coletar status atual do serviço
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
      register: status_atual

    - name: Exibir status atual
      ansible.builtin.debug:
        msg: "Status atual do serviço {{ servico_zabbix }} em {{ inventory_hostname }}: {{ status_atual.state }}"

    - name: Reiniciar serviço se estiver parado
      when: status_atual.state != 'running'
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
        state: restarted

    - name: Coletar status após o restart
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
      register: status_final

    - name: Exibir resumo no log do AWX
      ansible.builtin.debug:
        msg: |
          Serviço: {{ servico_zabbix }}
          Host: {{ inventory_hostname }}
          Status Antes: {{ status_atual.state }}
          Status Depois: {{ status_final.state }}
          Timestamp: {{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}
          Resultado: {{ 'Restart executado com sucesso' if status_atual.state != 'running' else 'Serviço já estava em execução, nenhuma ação necessária' }}
