---
- name: Reiniciar Serviço Windows (AWX — somente log em tela)
  hosts: "{{ host_alvo }}"
  gather_facts: yes

  tasks:
    - name: Coletar status ANTES do serviço
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
      register: status_antes

    - name: Reiniciar serviço se trigger for PROBLEM
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
        state: restarted

    - name: Coletar status DEPOIS do serviço
      ansible.windows.win_service:
        name: "{{ servico_zabbix }}"
      register: status_depois

    - name: Exibir resumo direto no log do AWX
      ansible.builtin.debug:
        msg: |
           Serviço: {{ servico_zabbix }}
           Host: {{ host_alvo }}
           Trigger: {{ status_trigger_zabbix }}
           Status Antes: {{ status_antes.state }}
           Status Depois: {{ status_depois.state }}
           Timestamp: {{ ansible_date_time.iso8601 }}
